export const DESIGN_WIDTH = 1024;

export const NAV_HEIGHT_BASE = 120;
export const BALL_SIZE_BASE = 68;
export const LINE_WIDTH_BASE = 6;
export const DASH_LENGTH_BASE = 36;
export const DASH_GAP_BASE = 40;
export const RISIKO_DASH_LENGTH_BASE = 30;
export const RISIKO_DASH_GAP_BASE = 26;
export const CENTER_LINE_DROP_BASE = 220;
export const TITLE_DIVERGE_BLACK_BASE = 120;
export const TITLE_DIVERGE_PURPLE_BASE = 160;
export const DESCRIPTION_GAP_BASE = 32;
export const TITLE_PX_DESIGN = 60;
export const DESC_PX_DESIGN = 26;
export const BALL_COL_W_BASE = 80;
export const INTRO_LOGO_W_BASE = 640;
export const NAV_LOGO_W_BASE = 170;
export const NAV_LOGO_H_BASE = 72;
export const NAV_BUTTON_PX_X = 80;
export const NAV_BUTTON_PX_Y = 16;
export const NAV_BUTTON_FONT = 22;
export const NAV_BUTTON_RADIUS = 20;
export const NAV_DIVIDER_H = 6;

export const SECTION_TITLE_PX_DESIGN = 88;
export const SECTION_TITLE_ENTER_PX_DESIGN = 164;
export const EXCLAMATION_W_BASE = 189;
export const EXCLAMATION_H_BASE = 568;
export const EXCLAMATION_DOT_X_RATIO = 34.5 / 189;
export const EXCLAMATION_DOT_Y_RATIO = 533.5 / 568;
export const QUESTION_W_BASE = 349;
export const QUESTION_H_BASE = 459;
export const QUESTION_DOT_X_RATIO = 119.5 / 349;
export const QUESTION_DOT_Y_RATIO = 424.5 / 459;
export const BRAIN_W_BASE = 232;
export const BRAIN_H_BASE = 516;
export const BRAIN_GAP_BASE = 64;
export const BRAIN_BALL_SIZE_BASE = 50;
export const BRAIN_HEADLINE_PX_DESIGN = 52;
export const BRAIN_VIDEO_W_BASE = 480;
export const BRAIN_VIDEO_H_BASE = 580;
export const BRAIN_VIDEO_RADIUS_BASE = 28;
export const BRAIN_VIDEO_BORDER_BASE = 5;
export const BRAIN_BALL_DROP_BASE = 440;
export const WAS_HUB_ENTER_DROP_BASE = 440;

export const WAS_ANDERS_TITLE_PX_DESIGN = 72;
export const WAS_ANDERS_TITLE_ENTER_PX_DESIGN = 132;
export const WAS_HUB_DOT_SIZE_BASE = 68;
export const WAS_HUB_RING_SIZE_BASE = 380;
export const WAS_HUB_RING_DASH_COUNT = 30;
export const WAS_HUB_GAP_BASE = 48;
export const WAS_VIDEO_GAP_BASE = 88;
export const WAS_HUB_BULLET_OFFSET_X_BASE = 300;
export const WAS_HUB_BULLET_OFFSET_Y_BASE = 72;
export const WAS_HUB_BULLET_MAX_W_BASE = 420;
export const WAS_HUB_BULLET_DOT_BASE = 20;
export const WAS_HUB_COLUMN_GAP_BASE = 152;
export const WAS_HUB_TEXT_COLUMN_GAP_BASE = 80;

export const ENTSCHEIDBAR_TITLE_PX_DESIGN = 72;
export const ENTSCHEIDBAR_TITLE_ENTER_PX_DESIGN = 104;
export const ENT_TREE_BALL_SIZE_BASE = 68;
export const ENT_TREE_LINE_W_BASE = 6;
export const ENT_TREE_TITLE_GAP_BASE = 48;
export const ENT_TREE_H_BRANCH_W_BASE = 280;
export const ENT_TREE_ICON_SIZE_BASE = 160;
export const ENT_TREE_BRANCH_GAP_BASE = 156;
export const ENT_TREE_FIRST_BRANCH_RATIO = 0.42;
export const ENT_TREE_TEXT_MAX_W_BASE = 380;
export const ENT_TREE_BRANCH_INNER_GAP_BASE = 24;
export const ENT_TREE_BULLET_DOT_BASE = 20;
export const ENT_TREE_SPINE_BOTTOM_BASE = 168;
export const ENT_TREE_ICON_LINE_NUDGE = 0.05;

export function scalePx(base: number, scale: number, min = 0): number {
  return Math.max(min, Math.round(base * scale));
}
